// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#define SECRET_DEVICE_KEY "your secret key feom arduino cloud"
#define SECRET_OPTIONAL_PASS "your wifi password"
#define SECRET_SSID "your wifi id"

const char DEVICE_LOGIN_NAME[]  = "1c8fa415-a2a9-4439-bf9b-4732087383e6";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAutoModeChange();
void onPompaChange();

String soilstatus;
int kelembapan;
int rawvalue;
bool autoMode;
bool pompa;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(soilstatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(kelembapan, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(rawvalue, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(autoMode, READWRITE, ON_CHANGE, onAutoModeChange);
  ArduinoCloud.addProperty(pompa, READWRITE, ON_CHANGE, onPompaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
