/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/62f083dd-59d8-4adb-a0ee-cca33bc10343 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String soilstatus;
  int kelembapan;
  int rawvalue;
  bool pompa;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "arduino_secrets.h"
#include "thingProperties.h"

const int soilAnalogPin = 36;
const int SAMPLES = 10;
const int relayPin = 23;

// Kalibrasi (ubah sesuai hasil uji)
int minWet = 600;   // raw sangat basah
int maxDry = 4095;  // raw sangat kering

// Threshold otomatis
int thresholdKering = 40; // < 40% = pompa ON otomatis

// Variabel untuk mencegah spam ON/OFF
// bool autoModeOverride = false;

int readSoilRaw() {
  long total = 0;
  for (int i = 0; i < SAMPLES; i++) {
    total += analogRead(soilAnalogPin);
    delay(5);
  }
  return total / SAMPLES;
}

void setup() {
  Serial.begin(115200);
  delay(1500);

  pinMode(relayPin, OUTPUT);
  digitalWrite(relayPin, LOW);   // Pompa OFF awal

  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  Serial.println("SYSTEM READY");
}

void loop() {
  ArduinoCloud.update();

  int raw = readSoilRaw();
  rawvalue = raw;

  raw = constrain(raw, minWet, maxDry);
  int percent = map(raw, minWet, maxDry, 100, 0);
  percent = constrain(percent, 0, 100);

  kelembapan = percent;

  if (percent > 70) soilstatus = "Basah";
  else if (percent > 40) soilstatus = "Normal";
  else soilstatus = "Kering";

  // ================= MODE AUTO =================
  if (autoMode) {
    if (percent < thresholdKering) {
      pompa = true;
      digitalWrite(relayPin, HIGH);   // Pompa ON
    } else {
      pompa = false;
      digitalWrite(relayPin, LOW);    // Pompa OFF
    }
  }

  // ================= DEBUG =================
  Serial.print("Raw: ");
  Serial.print(rawvalue);
  Serial.print(" | %: ");
  Serial.print(percent);
  Serial.print(" | Status: ");
  Serial.print(soilstatus);
  Serial.print(" | Mode: ");
  Serial.print(autoMode ? "AUTO" : "MANUAL");
  Serial.print(" | Pompa: ");
  Serial.println(digitalRead(relayPin) ? "ON" : "OFF");

  delay(2000);
}

/*
  Since Pompa is READ_WRITE variable, onPompaChange() is
  executed every time a new value is received from IoT Cloud.
*/

void onPompaChange() {
  if (!autoMode) {  
    digitalWrite(relayPin, pompa ? HIGH : LOW);
  }

  Serial.print("POMPA MANUAL: ");
  Serial.println(pompa ? "ON" : "OFF");
}

// ================= MODE SWITCH =================
void onAutoModeChange() {
  Serial.print("GANTI MODE: ");
  Serial.println(autoMode ? "AUTO" : "MANUAL");
}
