/* 
  Smart Plant Watering System using Arduino IoT Cloud
  ---------------------------------------------------
  This system automatically monitors soil moisture and controls
  a water pump using an ESP32 + relay module + soil sensor.
  It supports both AUTOMATIC mode (sensor-based control)
  and MANUAL mode (from IoT dashboard).

  Cloud Variables (auto-generated by Arduino IoT Cloud):
  - String soilstatus    → Soil condition: "Basah", "Normal", "Kering"
  - int kelembapan       → Moisture percentage
  - int rawvalue         → Raw ADC reading (0–4095)
  - bool pompa           → Pump On/Off (manual control)
*/

#include "arduino_secrets.h"
#include "thingProperties.h"

const int soilAnalogPin = 36;   // ADC pin VP on ESP32 used for soil sensor
const int SAMPLES = 10;         // Number of samples to average for smoothing
const int relayPin = 23;        // Digital pin connected to relay IN

// Calibration values (adjust based on testing)
int minWet = 600;               // Raw ADC reading when soil is fully wet
int maxDry = 4095;              // Raw ADC reading when soil is dry

// Soil dryness threshold (Auto Mode)
// If moisture < threshold → pump turns ON automatically
int thresholdKering = 40;       

// Function: readSoilRaw()
// Reads the soil sensor multiple times and returns the averaged value.
// Purpose: reduce noise and stabilize ADC reading.
int readSoilRaw() {
  long total = 0;

  for (int i = 0; i < SAMPLES; i++) {
    total += analogRead(soilAnalogPin); // Read analog input
    delay(5);                           // Small delay for stability
  }

  return total / SAMPLES;               // Return averaged raw value
}

// SETUP
// Runs once at startup.
void setup() {
  Serial.begin(115200); // Start serial communication for debugging
  delay(1500);

  pinMode(relayPin, OUTPUT);     // Set relay pin as output
  digitalWrite(relayPin, LOW);   // Start with pump OFF

  initProperties();               // Initialize IoT Cloud properties
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);        // Enable IoT debugging
  ArduinoCloud.printDebugInfo();

  Serial.println("SYSTEM READY");
}

// LOOP
// Runs continuously. Handles cloud sync, reads sensor, updates pump logic.
void loop() {
  ArduinoCloud.update();         // Sync with Arduino IoT Cloud

  // ----- Read Soil Moisture -----
  int raw = readSoilRaw();       // Get averaged raw ADC value
  rawvalue = raw;                // Send raw value to cloud

  // Constrain raw measurement between calibrated bounds
  raw = constrain(raw, minWet, maxDry);

  // Convert raw value into percentage moisture
  int percent = map(raw, minWet, maxDry, 100, 0);
  percent = constrain(percent, 0, 100);
  kelembapan = percent;          // Update cloud variable

  // ----- Determine Soil Status -----
  if (percent > 70)       soilstatus = "Basah";     // Wet
  else if (percent > 40)  soilstatus = "Normal";    // Medium
  else                    soilstatus = "Kering";    // Dry

  // ----- AUTO MODE Logic -----
  if (autoMode) {
    if (percent < thresholdKering) {
      pompa = true;                  // Auto ON
      digitalWrite(relayPin, HIGH);  // Activate relay
    } else {
      pompa = false;                 // Auto OFF
      digitalWrite(relayPin, LOW);   // Deactivate relay
    }
  }

  // ----- Debug Output -----
  Serial.print("Raw: ");
  Serial.print(rawvalue);
  Serial.print(" | %: ");
  Serial.print(percent);
  Serial.print(" | Status: ");
  Serial.print(soilstatus);
  Serial.print(" | Mode: ");
  Serial.print(autoMode ? "AUTO" : "MANUAL");
  Serial.print(" | Pompa: ");
  Serial.println(digitalRead(relayPin) ? "ON" : "OFF");

  delay(2000); // Delay between cycles
}

// onPompaChange()
// Triggered when the user toggles the pump from IoT Cloud in MANUAL mode.
void onPompaChange() {
  if (!autoMode) {                      // Only allow manual control if AUTO is OFF
    digitalWrite(relayPin, pompa ? HIGH : LOW);
  }

  Serial.print("POMPA MANUAL: ");
  Serial.println(pompa ? "ON" : "OFF");
}

// onAutoModeChange()
// Triggered when user switches between AUTO and MANUAL mode.
// Used for debugging or additional future logic.
void onAutoModeChange() {
  Serial.print("GANTI MODE: ");
  Serial.println(autoMode ? "AUTO" : "MANUAL");
}
